### ISSUE TITLE
Use of the Loupe within the DTRichTextEditor causes a crash

### ISSUE THREAD

**Issue by slm-2015** [Cocoanetics/DTLoupe#1]
Hi,

I am using the rich text editor (DTRichTextEditor) in our project and are experiencing an issue with the use of the magnifying glass loupe (i.e. cursor positioning function) that is causing our app to crash.

Here are the repro steps:
- Embed the rich text editor into a skeleton app that contains a view that holds the DTRichTextEditor component. You can find our example project that [does this here.](http://sendfile.pl/pobierz/400838---Xi7o.html)
- Start the app. Do not type any letters, just press and hold for a few seconds to bring out the loupe for cursor positioning.
- Lift your finger press to make the loupe disappear
- Press and hold again for a few seconds to bring out the loupe again.
- _Bug:_ This makes the project crash at: [DTLoupeView refreshLoupeContent] / [DTLoupeLayerDelegate displayLayer:]

The problem can appear on other occasions, but the steps above are the most reliable to reproduce the issue.  We are testing on iOS 8.  xcode 6.3 with iOS sdk 8.3

I'd would like to offer $200 USD to the person who can produce a fix for this issue.  If the fix requires a reimplementation the magnification using the modern snapshotting methods, I'd understand that this would need more work and would pay $800 USD instead of $200 USD.  Transfer of payment on a successful code review from Oliver and subject to final testing within my project.

Many thanks,
Simon.

**Comment by amro** [comment]
I think this is literally a one line fix, if you're okay with dropping support for iOS 6. I was able to reproduce quite regularly in the simulator in the original code. I switched to the new API and the crash went away.

**Comment by slm-2015** [comment]
Hi Amro,

Thanks for your note.  We do not support iOS 6 with our app, so it is ok for me.  Oliver?

Best,
Simon.

**Comment by amro** [comment]
Here's a pull request, in case the fix checks out for you as well. I used your sample to test. Just replace the line in the try block with the line from my patch and you should be good to try it.

https://github.com/Cocoanetics/DTLoupe/pull/2

**Comment by slm-2015** [comment]
Hi again,

Unfortunately it does not solve the problem very well.
Its not crashing anymore which is very good! but you can't see text inside the loupe anymore:( - at least on iOS 8

**Comment by amro** [comment]
Odd, I could see it in iOS 8 sim.

Edit: No, it seem to work. Are you testing on device?

**Comment by slm-2015** [comment]
Yes, showing nicely on simulators but not on device(ip5 iOS 7, ip6 iOS 8). One of those weird bugs..

**Comment by odrobnik** [comment]
I think it's got to do with the editor using CATiledLayer. Maybe this needs an update as well so that it would call the text rendering methods when rendering the hierarchy?

**Comment by amro** [comment]
That's one way to fix it but it looks like there's a bug in renderInContext: in iOS 8 that chokes on empty rects when rendering.

**Comment by odrobnik** [comment]
@amro please elaborate what you mean with "chokes on empty rects"... is that something we could prevent?

**Comment by amro** [comment]
Take another look when you have a chance. I tried to debug views after reproducing the crash and saw that the tools couldn't properly serialize some layers b/c they had NaN x or y positions. The crash can also happen if layers with frames equal to CGRectZero happen.

I'm not sure this is ultimately the right place to fix this problem. It might be that DTRichTextEditor needs to do additional validation on the frames of its layers. But fixing it here means DTLoupe will work with other views that have the same behavior.

Edit: Please see the new commit on my PR
Edit 2: Source - searching for the failure lead me to [this](https://github.com/nicklockwood/FXBlurView/issues/79), then I saw the debug info I mentioned above while debugging. 
Edit 3: I forgot to mention (and commit!) that this still requires renderInContext:.

**Comment by slm-2015** [comment]
This code fixes the crash and seems to be a good security if any layer with a wrong frame comes to rendering method. Thanks @amro. 

@Cocoanetics what do you think?

Thanks.

**Comment by slm-2015** [comment]
hi @amro and @coconetics,

Hope you are both well.

@amro, we have been testing your proposed fix a lot more over the last few days.  It is working well on iOS 8 and iOS 7. While not critical for us now, but it would be valuable to have your opinion on, is the fix does not work on the current Beta of iOS 9.  On our test iOS 9 device, the loupe displays a black image within it (no text) and in fact crashes on the simulator.  Would be great to get any early thoughts on that.

@coconetics, would love your opinion on @amro changes when you get a spare moment so we can wrap this up and get amro some $ :-).

Thanks guys!

**Comment by amro** [comment]
@slm-2015 Odd. I just tried my change in your test project on my iPhone 6 running iOS 9b1 and it worked great. It worked fine in the sim as well. I did have to change line 106 in DTRichTextEditorView.m from `__unsafe_unretained` to `__weak` before it would build though. Is this the test you ran or did you do something else?

**Comment by slm-2015** [comment]
@amro Hey sorry i was testing the loupe in a project with a bit more complicated view hierarchy. 
Prepared a sample project that is demonstrating the problem here: http://sendfile.pl/pobierz/412005---zR7B.html
Managed to produce an adhoc fix in DTLoupeView.m line 244 which basically limits the depth of searching for a rootView but probably thats not the best way to fix it.
Any thoughts you had on a better way to fix it would be great.

**Comment by amro** [comment]
With your change (line 243 - "return view.superview.superview") still commented, it still works for me. I'm on iOS 9 beta 2 using an iPhone 6. The same is true in the simulator. It seems this is a little tougher to reproduce. You're on beta 2 and using Xcode build 7A121l, right?

**Comment by slm-2015** [comment]
Yes Xcode beta 2 build 7A121l. Its easier to get it on the iPad, both device and simulator.

**Comment by amro** [comment]
I see. I was able to reproduce the black image issue in the iPad sim. Commenting out my change did not resolve it so I believe it's a separate problem unrelated to this issue. I don't have a lot of time to look into this one immediately but I did try a few things to no avail.

**Comment by slm-2015** [comment]
hi @amro ,

Thanks for your response on the iOS 9 issue.  Let's wrap up on this problem first then.  @Cocoanetics, would love your thoughts on the code changes from amro.

Many thanks,
Simon.

**Comment by odrobnik** [comment]
hi @slm-2015 - I trust @amro implicitly, he is one of the big contributors to DTCoreText where he implemented cascading CSS support. So if that fixes the issue, then I am good.

I believe that we still want to be able to use the modern way of snapshotting, but the CATiledLayer used to display it needs to draw its content on the main thread when the snapshotting method recurses to it.

So, step 1 would be to merge this fix - if you can verify that the crashes no longer occur.

**Comment by slm-2015** [comment]
Thanks all. @amro I have emailed you separately to ask for your payment details.  @Cocoanetics - we will be happy to retest once you have merged the changes.  Cheers.

**Comment by Daij-Djan** [comment]
this didn't work for me on is and issue #8 describes the fix - which isn't in DTLoupe -- for me hideInvalidLayersInView isn't needed either :) [though it won't hurt :D]
