### ISSUE TITLE
Loupe Graphics need iOS 8 modernization

### ISSUE THREAD

**Issue by odrobnik** [Cocoanetics/DTLoupe#3]
The graphics used for the magnifying glass are still from pre iOS 7. The need to be modernized.

**Comment by rmaddy** [comment]
Attached are updated 1x, 2x, and 3x images based on screen captures from iOS 9.3. I also made the following code changes to accommodate these updated images (Sorry, I don't know git enough to make a pull request for this stuff):

All in DTLoupeView.m:

Line 137 change to:

`_loupeContentsMaskLayer.transform = CATransform3DMakeScale(1.0f, 1.0f, 1.0f);`

Line 200 change to:

`return CGPointMake(0, -65.0);`

Line 219 change to:

`return CGPointMake(0, 0.0);`

[loupe_images.zip](https://github.com/Cocoanetics/DTLoupe/files/299209/loupe_images.zip)

**Comment by odrobnik** [comment]
@rmaddy would you mind read my guide and try to add these changes to the pull release? 

https://www.cocoanetics.com/2012/01/github-fork-fix-pull-request/

**Comment by rmaddy** [comment]
Done. Thanks for the instructions.

**Comment by odrobnik** [comment]
@rmaddy Too me only one-and-a-half years to merge this...
