### ISSUE TITLE
iOS 9 crash when loupe is shown

### ISSUE THREAD

**Issue by artonragsdale** [Cocoanetics/DTLoupe#7]
On iOS 9, whenever the loupe tries to appear, the app crashes during renderInContext(DTLoupeView.m line 584 due to views in hierarchy having (inf,inf) positions.

**Comment by odrobnik** [comment]
Isn't there code that hides invalid layers?

**Comment by artonragsdale** [comment]
It doesn't seem to be hiding everything it needs to. I'm not sure why.

**Comment by odrobnik** [comment]
@amro didn't your code take care of this?

**Comment by amro** [comment]
Only for iOS 8, if I recall. Nine beta 1 or 3 had some different issue.

Thanks,
Amro

**Comment by amro** [comment]
Okay - IIRC on iOS 8 the issue was (NaN, NaN) - not (inf, inf). I can attempt to fix it but I will not have time today. Maybe tomorrow or late Monday.

**Comment by amro** [comment]
I looked at this a bit. It seems iOS 9 is even less lenient than iOS 8. Hidden layers with invalid frames cause an exception. The code from my prior patch is actually hiding the layers appropriately.

I think there's a bug someplace in DTRTE that is introducing these invalid layers, though we should guard against it here somehow defensively. How do we do that? I'm not sure. I did try removing the invalid layers - that worked in that it got farther, but it then crashed in DTRTE code instead.

Would you like me to provide a pull request that removes the invalid layers?

[Sample project](https://dl.dropboxusercontent.com/u/3700270/RichTextTestProject.zip)

**Comment by odrobnik** [comment]
As always, a pull request is welcome.

**Comment by odrobnik** [comment]
PS: maybe there is a way to correct the frames of the layers to CGRectZero instead of removing them, @amro?

**Comment by amro** [comment]
Setting the size to CGRectZero doesn't help here. Removing the views in question, as @Wielkibrat found, is needed.
